#!/bin/bash

echo "🚀 Dashboard Fix Instructions"
echo "============================"
echo ""
echo "Since SSH is blocked, use the Hetzner web console:"
echo ""
echo "1. Open this URL in your browser:"
echo "   https://web-console.hetzner.cloud/pp?data=0y5x9bbUh4btAKax0vzeya2QQcyUWwwe2JU%2Bbb4GmTrbRn7yqePiLC7nGaqaNy689PZoban9XXz7yZvMv4zO5DRUiTbt9O6yxITz31mxxEP69ClAQV6SUTO0%2BMtWD7J17A2c8HmF%2FwIdxn8NWjNV83yoewh6&nonce=lXOdr87sAe%2FwVZSG&tag=94RcZq4Pu6dAWXIUSqm2VQ%3D%3D"
echo ""
echo "2. When prompted, enter VNC password: WwkTq4fC"
echo ""
echo "3. Login as root in the console"
echo ""
echo "4. Run these commands:"
echo "   cd /var/www/passkey-server"
echo "   git pull origin main"
echo "   pm2 restart passkey-server"
echo ""
echo "5. Check SSH service (optional):"
echo "   systemctl status ssh"
echo "   systemctl restart ssh"
echo ""
echo "The dashboard fix changes API_BASE from 'https://localhost' to window.location.origin"
echo ""
echo "Alternative: Open a new console with:"
echo "export HCLOUD_TOKEN=\"gccoW05Jpq5cJrrZtRrKDxDzcrYFkSj7XQREN3DeqVXsFYz5QPESt4FX3zD3QG9i\""
echo "hcloud server request-console passkey-server-20250726-164012"